// Generated by development/build-storage-codec.mjs; do not edit.
// Playwright 1.60.0, Copyright Microsoft Corporation, Apache-2.0.
// See playwright-storage-LICENSE.txt and development/vendor/playwright.
export async function storageCodec({ mode, state }) {
/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

function isRegExp(obj     )                {
  try {
    return obj instanceof RegExp || Object.prototype.toString.call(obj) === '[object RegExp]';
  } catch (error) {
    return false;
  }
}

function isDate(obj     )              {
  try {
    // eslint-disable-next-line no-restricted-globals
    return obj instanceof Date || Object.prototype.toString.call(obj) === '[object Date]';
  } catch (error) {
    return false;
  }
}

function isURL(obj     )             {
  try {
    return obj instanceof URL || Object.prototype.toString.call(obj) === '[object URL]';
  } catch (error) {
    return false;
  }
}

function isError(obj     )               {
  try {
    return obj instanceof Error || (obj && Object.getPrototypeOf(obj)?.name === 'Error');
  } catch (error) {
    return false;
  }
}

function isTypedArray(obj     , constructor          )          {
  try {
    return obj instanceof constructor || Object.prototype.toString.call(obj) === `[object ${constructor.name}]`;
  } catch (error) {
    return false;
  }
}

function isArrayBuffer(obj     )                     {
  try {
    return obj instanceof ArrayBuffer || Object.prototype.toString.call(obj) === '[object ArrayBuffer]';
  } catch (error) {
    return false;
  }
}

const typedArrayConstructors                                   = {
  i8: Int8Array,
  ui8: Uint8Array,
  ui8c: Uint8ClampedArray,
  i16: Int16Array,
  ui16: Uint16Array,
  i32: Int32Array,
  ui32: Uint32Array,
  // TODO: add Float16Array once it's in baseline
  f32: Float32Array,
  f64: Float64Array,
  bi64: BigInt64Array,
  bui64: BigUint64Array,
};

function typedArrayToBase64(array     ) {
  /**
   * Firefox does not support iterating over typed arrays, so we use `.toBase64`.
   * Error: 'Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto().'
   */
  if ('toBase64' in array)
    return array.toBase64();
  const binary = Array.from(new Uint8Array(array.buffer, array.byteOffset, array.byteLength)).map(b => String.fromCharCode(b)).join('');
  return btoa(binary);
}

function base64ToTypedArray(base64        , TypedArrayConstructor     ) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++)
    bytes[i] = binary.charCodeAt(i);
  return new TypedArrayConstructor(bytes.buffer);
}

function parseEvaluationResultValue(value                 , handles        = [], refs                      = new Map())      {
  if (Object.is(value, undefined))
    return undefined;
  if (typeof value === 'object' && value) {
    if ('ref' in value)
      return refs.get(value.ref);
    if ('v' in value) {
      if (value.v === 'undefined')
        return undefined;
      if (value.v === 'null')
        return null;
      if (value.v === 'NaN')
        return NaN;
      if (value.v === 'Infinity')
        return Infinity;
      if (value.v === '-Infinity')
        return -Infinity;
      if (value.v === '-0')
        return -0;
      return undefined;
    }
    if ('d' in value) {
      // eslint-disable-next-line no-restricted-globals
      return new Date(value.d);
    }
    if ('u' in value)
      return new URL(value.u);
    if ('bi' in value)
      return BigInt(value.bi);
    if ('e' in value) {
      const error = new Error(value.e.m);
      error.name = value.e.n;
      error.stack = value.e.s;
      return error;
    }
    if ('r' in value)
      return new RegExp(value.r.p, value.r.f);
    if ('a' in value) {
      const result        = [];
      refs.set(value.id, result);
      for (const a of value.a)
        result.push(parseEvaluationResultValue(a, handles, refs));
      return result;
    }
    if ('o' in value) {
      const result      = {};
      refs.set(value.id, result);
      for (const { k, v } of value.o) {
        if (k === '__proto__')
          continue;
        result[k] = parseEvaluationResultValue(v, handles, refs);
      }
      return result;
    }
    if ('h' in value)
      return handles[value.h];
    if ('ta' in value)
      return base64ToTypedArray(value.ta.b, typedArrayConstructors[value.ta.k]);
    if ('ab' in value)
      return base64ToTypedArray(value.ab.b, Uint8Array).buffer;
  }
  return value;
}

function serializeAsCallArgument(value     , handleSerializer                               )                  {
  return serialize(value, handleSerializer, { visited: new Map(), lastId: 0 });
}

function serialize(value     , handleSerializer                               , visitorInfo             )                  {
  if (value && typeof value === 'object') {
    // eslint-disable-next-line no-restricted-globals
    if (typeof globalThis.Window === 'function' && value instanceof globalThis.Window)
      return 'ref: <Window>';
    // eslint-disable-next-line no-restricted-globals
    if (typeof globalThis.Document === 'function' && value instanceof globalThis.Document)
      return 'ref: <Document>';
    // eslint-disable-next-line no-restricted-globals
    if (typeof globalThis.Node === 'function' && value instanceof globalThis.Node)
      return 'ref: <Node>';
  }
  return innerSerialize(value, handleSerializer, visitorInfo);
}

function innerSerialize(value     , handleSerializer                               , visitorInfo             )                  {
  const result = handleSerializer(value);
  if ('fallThrough' in result)
    value = result.fallThrough;
  else
    return result;

  if (typeof value === 'symbol')
    return { v: 'undefined' };
  if (Object.is(value, undefined))
    return { v: 'undefined' };
  if (Object.is(value, null))
    return { v: 'null' };
  if (Object.is(value, NaN))
    return { v: 'NaN' };
  if (Object.is(value, Infinity))
    return { v: 'Infinity' };
  if (Object.is(value, -Infinity))
    return { v: '-Infinity' };
  if (Object.is(value, -0))
    return { v: '-0' };

  if (typeof value === 'boolean')
    return value;
  if (typeof value === 'number')
    return value;
  if (typeof value === 'string')
    return value;
  if (typeof value === 'bigint')
    return { bi: value.toString() };

  if (isError(value)) {
    let stack;
    if (value.stack?.startsWith(value.name + ': ' + value.message)) {
      // v8
      stack = value.stack;
    } else {
      stack = `${value.name}: ${value.message}\n${value.stack}`;
    }
    return { e: { n: value.name, m: value.message, s: stack } };
  }
  if (isDate(value))
    return { d: value.toJSON() };
  if (isURL(value))
    return { u: value.toJSON() };
  if (isRegExp(value))
    return { r: { p: value.source, f: value.flags } };
  for (const [k, ctor] of Object.entries(typedArrayConstructors)                                ) {
    if (isTypedArray(value, ctor))
      return { ta: { b: typedArrayToBase64(value), k } };
  }
  if (isArrayBuffer(value))
    return { ab: { b: typedArrayToBase64(new Uint8Array(value)) } };

  const id = visitorInfo.visited.get(value);
  if (id)
    return { ref: id };

  if (Array.isArray(value)) {
    const a = [];
    const id = ++visitorInfo.lastId;
    visitorInfo.visited.set(value, id);
    for (let i = 0; i < value.length; ++i)
      a.push(serialize(value[i], handleSerializer, visitorInfo));
    return { a, id };
  }

  if (typeof value === 'object') {
    const o                                      = [];
    const id = ++visitorInfo.lastId;
    visitorInfo.visited.set(value, id);
    for (const name of Object.keys(value)) {
      let item;
      try {
        item = value[name];
      } catch (e) {
        continue;  // native bindings will throw sometimes
      }
      if (name === 'toJSON' && typeof item === 'function')
        o.push({ k: name, v: { o: [], id: 0 } });
      else
        o.push({ k: name, v: serialize(item, handleSerializer, visitorInfo) });
    }

    let jsonWrapper;
    try {
      // If Object.keys().length === 0 we fall back to toJSON if it exists
      if (o.length === 0 && value.toJSON && typeof value.toJSON === 'function')
        jsonWrapper = { value: value.toJSON() };
    } catch (e) {
    }
    if (jsonWrapper)
      return innerSerialize(jsonWrapper.value, handleSerializer, visitorInfo);

    return { o, id };
  }
}
/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

class StorageScript {
          _isFirefox         ;
          _global;

  constructor(isFirefox         ) {
    this._isFirefox = isFirefox;
    // eslint-disable-next-line no-restricted-globals
    this._global = globalThis;
  }

          _idbRequestToPromise                                         (request   ) {
    return new Promise             ((resolve, reject) => {
      request.addEventListener('success', () => resolve(request.result));
      request.addEventListener('error', () => reject(request.error));
    });
  }

          _isPlainObject(v     ) {
    const ctor = v?.constructor;
    if (this._isFirefox) {
      const constructorImpl = ctor?.toString()                      ;
      if (constructorImpl?.startsWith('function Object() {') && constructorImpl?.includes('[native code]'))
        return true;
    }
    return ctor === Object;
  }

          _trySerialize(value     )                                   {
    let trivial = true;
    const encoded = serializeAsCallArgument(value, v => {
      const isTrivial = (
        this._isPlainObject(v)
        || Array.isArray(v)
        || typeof v === 'string'
        || typeof v === 'number'
        || typeof v === 'boolean'
        || Object.is(v, null)
      );

      if (!isTrivial)
        trivial = false;

      return { fallThrough: v };
    });
    if (trivial)
      return { trivial: value };
    return { encoded };
  }

          async _collectDB(dbInfo                 ) {
    if (!dbInfo.name)
      throw new Error('Database name is empty');
    if (!dbInfo.version)
      throw new Error('Database version is unset');

    const db = await this._idbRequestToPromise(indexedDB.open(dbInfo.name));
    if (db.objectStoreNames.length === 0)
      return { name: dbInfo.name, version: dbInfo.version, stores: [] };

    const transaction = db.transaction(db.objectStoreNames, 'readonly');
    const stores = await Promise.all([...db.objectStoreNames].map(async storeName => {
      const objectStore = transaction.objectStore(storeName);

      const keys = await this._idbRequestToPromise(objectStore.getAllKeys());
      const records = await Promise.all(keys.map(async key => {
        const record                                                        = {};

        if (objectStore.keyPath === null) {
          const { encoded, trivial } = this._trySerialize(key);
          if (trivial)
            record.key = trivial;
          else
            record.keyEncoded = encoded;
        }

        const value = await this._idbRequestToPromise(objectStore.get(key));
        const { encoded, trivial } = this._trySerialize(value);
        if (trivial)
          record.value = trivial;
        else
          record.valueEncoded = encoded;

        return record;
      }));

      const indexes = [...objectStore.indexNames].map(indexName => {
        const index = objectStore.index(indexName);
        return {
          name: index.name,
          keyPath: typeof index.keyPath === 'string' ? index.keyPath : undefined,
          keyPathArray: Array.isArray(index.keyPath) ? index.keyPath : undefined,
          multiEntry: index.multiEntry,
          unique: index.unique,
        };
      });

      return {
        name: storeName,
        records: records,
        indexes,
        autoIncrement: objectStore.autoIncrement,
        keyPath: typeof objectStore.keyPath === 'string' ? objectStore.keyPath : undefined,
        keyPathArray: Array.isArray(objectStore.keyPath) ? objectStore.keyPath : undefined,
      };
    }));

    return {
      name: dbInfo.name,
      version: dbInfo.version,
      stores,
    };
  }

  async collect(recordIndexedDB         )                             {
    const localStorage = Object.keys(this._global.localStorage).map(name => ({ name, value: this._global.localStorage.getItem(name)  }));
    if (!recordIndexedDB)
      return { localStorage };
    try {
      const databases = await this._global.indexedDB.databases();
      const indexedDB = await Promise.all(databases.map(db => this._collectDB(db)));
      return { localStorage, indexedDB };
    } catch (e) {
      throw new Error('Unable to serialize IndexedDB: ' + e.message);
    }
  }

          async _restoreDB(dbInfo                            ) {
    const openRequest = this._global.indexedDB.open(dbInfo.name, dbInfo.version);
    openRequest.addEventListener('upgradeneeded', () => {
      const db = openRequest.result;
      for (const store of dbInfo.stores) {
        const objectStore = db.createObjectStore(store.name, { autoIncrement: store.autoIncrement, keyPath: store.keyPathArray ?? store.keyPath });
        for (const index of store.indexes)
          objectStore.createIndex(index.name, index.keyPathArray ?? index.keyPath , { unique: index.unique, multiEntry: index.multiEntry });
      }
    });

    // after `upgradeneeded` finishes, `success` event is fired.
    const db = await this._idbRequestToPromise(openRequest);

    if (db.objectStoreNames.length === 0)
      return;
    const transaction = db.transaction(db.objectStoreNames, 'readwrite');
    await Promise.all(dbInfo.stores.map(async store => {
      const objectStore = transaction.objectStore(store.name);
      await Promise.all(store.records.map(async record => {
        await this._idbRequestToPromise(
            objectStore.add(
                record.value ?? parseEvaluationResultValue(record.valueEncoded),
                record.key ?? parseEvaluationResultValue(record.keyEncoded),
            )
        );
      }));
    }));
  }

  async restore(originState                                       ) {
    // Clean Service Workers.
    const registrations = this._global.navigator.serviceWorker ? await this._global.navigator.serviceWorker.getRegistrations() : [];
    await Promise.all(registrations.map(async r => {
      // Heuristic for service workers that stalled during main script fetch or importScripts:
      // Waiting for them to finish unregistering takes ages so we do not await.
      // However, they will unregister immediately after fetch finishes and should not affect next page load.
      // Unfortunately, loading next page in Chromium still takes 5 seconds waiting for
      // some operation on this bogus service worker to finish.
      if (!r.installing && !r.waiting && !r.active)
        r.unregister().catch(() => {});
      else
        await r.unregister().catch(() => {});
    }));

    try {
      for (const db of await this._global.indexedDB.databases?.() || []) {
        // Do not wait for the callback - it is called on timer in Chromium (slow).
        if (db.name)
          this._global.indexedDB.deleteDatabase(db.name );
      }
      await Promise.all((originState?.indexedDB ?? []).map(dbInfo => this._restoreDB(dbInfo)));
    } catch (e) {
      throw new Error('Unable to restore IndexedDB: ' + e.message);
    }

    this._global.sessionStorage.clear();
    this._global.localStorage.clear();
    for (const { name, value } of (originState?.localStorage || []))
      this._global.localStorage.setItem(name, value);
  }
}
const script = new StorageScript(false);
if (mode === 'restore') return script.restore(state);
if (mode === 'collect') return script.collect(true);
throw new Error('storage_codec_operation_rejected');
}
